using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Bem.Core;
using Bem.Exceptions;
using Bem.Models.Errors;

namespace Bem.Models.Webhooks;

[JsonConverter(
    typeof(JsonModelConverter<
        CollectionProcessingWebhookEvent,
        CollectionProcessingWebhookEventFromRaw
    >)
)]
public sealed record class CollectionProcessingWebhookEvent : JsonModel
{
    /// <summary>
    /// Unique identifier of the collection.
    /// </summary>
    public required string CollectionID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("collectionID");
        }
        init { this._rawData.Set("collectionID", value); }
    }

    /// <summary>
    /// Name/path of the collection.
    /// </summary>
    public required string CollectionName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("collectionName");
        }
        init { this._rawData.Set("collectionName", value); }
    }

    /// <summary>
    /// Unique ID generated by bem to identify the event.
    /// </summary>
    public required string EventID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("eventID");
        }
        init { this._rawData.Set("eventID", value); }
    }

    /// <summary>
    /// The operation performed (add or update).
    /// </summary>
    public required ApiEnum<string, Operation> Operation
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ApiEnum<string, Operation>>("operation");
        }
        init { this._rawData.Set("operation", value); }
    }

    /// <summary>
    /// Number of items successfully processed.
    /// </summary>
    public required long ProcessedCount
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("processedCount");
        }
        init { this._rawData.Set("processedCount", value); }
    }

    /// <summary>
    /// The unique ID you use internally to refer to this data point, propagated from
    /// the original function input.
    /// </summary>
    public required string ReferenceID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("referenceID");
        }
        init { this._rawData.Set("referenceID", value); }
    }

    /// <summary>
    /// Processing status (success or failed).
    /// </summary>
    public required ApiEnum<string, CollectionProcessingWebhookEventStatus> Status
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<
                ApiEnum<string, CollectionProcessingWebhookEventStatus>
            >("status");
        }
        init { this._rawData.Set("status", value); }
    }

    /// <summary>
    /// Array of collection item KSUIDs that were added or updated.
    /// </summary>
    public IReadOnlyList<string>? CollectionItemIds
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<string>>("collectionItemIDs");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set<ImmutableArray<string>?>(
                "collectionItemIDs",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// Timestamp indicating when the event was created.
    /// </summary>
    public DateTimeOffset? CreatedAt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<DateTimeOffset>("createdAt");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("createdAt", value);
        }
    }

    /// <summary>
    /// Error message if processing failed.
    /// </summary>
    public string? ErrorMessage
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("errorMessage");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("errorMessage", value);
        }
    }

    public ApiEnum<string, CollectionProcessingWebhookEventEventType>? EventType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<
                ApiEnum<string, CollectionProcessingWebhookEventEventType>
            >("eventType");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("eventType", value);
        }
    }

    /// <summary>
    /// The attempt number of the function call that created this event. 1 indexed.
    /// </summary>
    public long? FunctionCallTryNumber
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("functionCallTryNumber");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionCallTryNumber", value);
        }
    }

    /// <summary>
    /// The inbound email that triggered this event.
    /// </summary>
    public InboundEmailEvent? InboundEmail
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<InboundEmailEvent>("inboundEmail");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("inboundEmail", value);
        }
    }

    public CollectionProcessingWebhookEventMetadata? Metadata
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<CollectionProcessingWebhookEventMetadata>(
                "metadata"
            );
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("metadata", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.CollectionID;
        _ = this.CollectionName;
        _ = this.EventID;
        this.Operation.Validate();
        _ = this.ProcessedCount;
        _ = this.ReferenceID;
        this.Status.Validate();
        _ = this.CollectionItemIds;
        _ = this.CreatedAt;
        _ = this.ErrorMessage;
        this.EventType?.Validate();
        _ = this.FunctionCallTryNumber;
        this.InboundEmail?.Validate();
        this.Metadata?.Validate();
    }

    public CollectionProcessingWebhookEvent() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public CollectionProcessingWebhookEvent(
        CollectionProcessingWebhookEvent collectionProcessingWebhookEvent
    )
        : base(collectionProcessingWebhookEvent) { }
#pragma warning restore CS8618

    public CollectionProcessingWebhookEvent(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    CollectionProcessingWebhookEvent(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="CollectionProcessingWebhookEventFromRaw.FromRawUnchecked"/>
    public static CollectionProcessingWebhookEvent FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class CollectionProcessingWebhookEventFromRaw : IFromRawJson<CollectionProcessingWebhookEvent>
{
    /// <inheritdoc/>
    public CollectionProcessingWebhookEvent FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => CollectionProcessingWebhookEvent.FromRawUnchecked(rawData);
}

/// <summary>
/// The operation performed (add or update).
/// </summary>
[JsonConverter(typeof(OperationConverter))]
public enum Operation
{
    Add,
    Update,
}

sealed class OperationConverter : JsonConverter<Operation>
{
    public override Operation Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "add" => Operation.Add,
            "update" => Operation.Update,
            _ => (Operation)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        Operation value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                Operation.Add => "add",
                Operation.Update => "update",
                _ => throw new BemInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// Processing status (success or failed).
/// </summary>
[JsonConverter(typeof(CollectionProcessingWebhookEventStatusConverter))]
public enum CollectionProcessingWebhookEventStatus
{
    Success,
    Failed,
}

sealed class CollectionProcessingWebhookEventStatusConverter
    : JsonConverter<CollectionProcessingWebhookEventStatus>
{
    public override CollectionProcessingWebhookEventStatus Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "success" => CollectionProcessingWebhookEventStatus.Success,
            "failed" => CollectionProcessingWebhookEventStatus.Failed,
            _ => (CollectionProcessingWebhookEventStatus)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CollectionProcessingWebhookEventStatus value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CollectionProcessingWebhookEventStatus.Success => "success",
                CollectionProcessingWebhookEventStatus.Failed => "failed",
                _ => throw new BemInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

[JsonConverter(typeof(CollectionProcessingWebhookEventEventTypeConverter))]
public enum CollectionProcessingWebhookEventEventType
{
    CollectionProcessing,
}

sealed class CollectionProcessingWebhookEventEventTypeConverter
    : JsonConverter<CollectionProcessingWebhookEventEventType>
{
    public override CollectionProcessingWebhookEventEventType Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "collection_processing" =>
                CollectionProcessingWebhookEventEventType.CollectionProcessing,
            _ => (CollectionProcessingWebhookEventEventType)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CollectionProcessingWebhookEventEventType value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CollectionProcessingWebhookEventEventType.CollectionProcessing =>
                    "collection_processing",
                _ => throw new BemInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

[JsonConverter(
    typeof(JsonModelConverter<
        CollectionProcessingWebhookEventMetadata,
        CollectionProcessingWebhookEventMetadataFromRaw
    >)
)]
public sealed record class CollectionProcessingWebhookEventMetadata : JsonModel
{
    public double? DurationFunctionToEventSeconds
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>("durationFunctionToEventSeconds");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("durationFunctionToEventSeconds", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.DurationFunctionToEventSeconds;
    }

    public CollectionProcessingWebhookEventMetadata() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public CollectionProcessingWebhookEventMetadata(
        CollectionProcessingWebhookEventMetadata collectionProcessingWebhookEventMetadata
    )
        : base(collectionProcessingWebhookEventMetadata) { }
#pragma warning restore CS8618

    public CollectionProcessingWebhookEventMetadata(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    CollectionProcessingWebhookEventMetadata(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="CollectionProcessingWebhookEventMetadataFromRaw.FromRawUnchecked"/>
    public static CollectionProcessingWebhookEventMetadata FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class CollectionProcessingWebhookEventMetadataFromRaw
    : IFromRawJson<CollectionProcessingWebhookEventMetadata>
{
    /// <inheritdoc/>
    public CollectionProcessingWebhookEventMetadata FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => CollectionProcessingWebhookEventMetadata.FromRawUnchecked(rawData);
}
