using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Bem.Core;
using Bem.Exceptions;
using Bem.Models.Errors;
using Bem.Models.Outputs;

namespace Bem.Models.Webhooks;

/// <summary>
/// Emitted when a `parse` function completes. Reuses the `extract` event shape on
/// the wire — both wrap a Transformation and downstream consumers care about the
/// same `transformedContent` payload — but uses a distinct `eventType` discriminator
/// so receivers can dispatch on the function type that produced it.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<ParseWebhookEvent, ParseWebhookEventFromRaw>))]
public sealed record class ParseWebhookEvent : JsonModel
{
    /// <summary>
    /// Unique ID generated by bem to identify the event.
    /// </summary>
    public required string EventID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("eventID");
        }
        init { this._rawData.Set("eventID", value); }
    }

    /// <summary>
    /// Unique identifier of function that this event is associated with.
    /// </summary>
    public required string FunctionID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("functionID");
        }
        init { this._rawData.Set("functionID", value); }
    }

    /// <summary>
    /// Unique name of function that this event is associated with.
    /// </summary>
    public required string FunctionName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("functionName");
        }
        init { this._rawData.Set("functionName", value); }
    }

    /// <summary>
    /// The number of items that were parsed. Used for batch parsing to indicate how
    /// many items were parsed.
    /// </summary>
    public required long ItemCount
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("itemCount");
        }
        init { this._rawData.Set("itemCount", value); }
    }

    /// <summary>
    /// The offset of the first item that was parsed. Used for batch parsing to indicate
    /// which item in the batch this event corresponds to.
    /// </summary>
    public required long ItemOffset
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("itemOffset");
        }
        init { this._rawData.Set("itemOffset", value); }
    }

    /// <summary>
    /// The unique ID you use internally to refer to this data point, propagated from
    /// the original function input.
    /// </summary>
    public required string ReferenceID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("referenceID");
        }
        init { this._rawData.Set("referenceID", value); }
    }

    /// <summary>
    /// The parsed content of the input. Top-level keys are `sections`, `entities`,
    /// and `relationships`; the precise shape is determined by the parse function's configuration.
    /// </summary>
    public required JsonElement TransformedContent
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("transformedContent");
        }
        init { this._rawData.Set("transformedContent", value); }
    }

    /// <summary>
    /// Average confidence score across all parsed fields, in the range [0, 1].
    /// </summary>
    public float? AvgConfidence
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<float>("avgConfidence");
        }
        init { this._rawData.Set("avgConfidence", value); }
    }

    /// <summary>
    /// Unique identifier of workflow call that this event is associated with.
    /// </summary>
    public string? CallID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("callID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("callID", value);
        }
    }

    /// <summary>
    /// Corrected feedback provided for fine-tuning purposes.
    /// </summary>
    public ParseWebhookEventCorrectedContent? CorrectedContent
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ParseWebhookEventCorrectedContent>(
                "correctedContent"
            );
        }
        init { this._rawData.Set("correctedContent", value); }
    }

    /// <summary>
    /// Timestamp indicating when the event was created.
    /// </summary>
    public DateTimeOffset? CreatedAt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<DateTimeOffset>("createdAt");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("createdAt", value);
        }
    }

    public ApiEnum<string, ParseWebhookEventEventType>? EventType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, ParseWebhookEventEventType>>(
                "eventType"
            );
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("eventType", value);
        }
    }

    /// <summary>
    /// Per-field bounding boxes. A JSON object mapping RFC 6901 JSON Pointer paths
    /// to the document regions from which each parsed value was sourced.
    /// </summary>
    public JsonElement? FieldBoundingBoxes
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<JsonElement>("fieldBoundingBoxes");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("fieldBoundingBoxes", value);
        }
    }

    /// <summary>
    /// Per-field confidence scores. A JSON object mapping RFC 6901 JSON Pointer paths
    /// to float values in the range [0, 1] indicating the model's confidence in each
    /// parsed field value.
    /// </summary>
    public JsonElement? FieldConfidences
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<JsonElement>("fieldConfidences");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("fieldConfidences", value);
        }
    }

    /// <summary>
    /// Unique identifier of function call that this event is associated with.
    /// </summary>
    public string? FunctionCallID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("functionCallID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionCallID", value);
        }
    }

    /// <summary>
    /// The attempt number of the function call that created this event. 1 indexed.
    /// </summary>
    public long? FunctionCallTryNumber
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("functionCallTryNumber");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionCallTryNumber", value);
        }
    }

    /// <summary>
    /// Version number of function that this event is associated with.
    /// </summary>
    public long? FunctionVersionNum
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("functionVersionNum");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionVersionNum", value);
        }
    }

    /// <summary>
    /// The inbound email that triggered this event.
    /// </summary>
    public InboundEmailEvent? InboundEmail
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<InboundEmailEvent>("inboundEmail");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("inboundEmail", value);
        }
    }

    /// <summary>
    /// Array of parse inputs with their types and S3 URLs.
    /// </summary>
    public IReadOnlyList<ParseWebhookEventInput>? Inputs
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<ParseWebhookEventInput>>(
                "inputs"
            );
        }
        init
        {
            this._rawData.Set<ImmutableArray<ParseWebhookEventInput>?>(
                "inputs",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// The input type of the content you're sending for transformation.
    /// </summary>
    public ApiEnum<string, InputType>? InputType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, InputType>>("inputType");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("inputType", value);
        }
    }

    /// <summary>
    /// List of properties that were invalid in the input.
    /// </summary>
    public IReadOnlyList<string>? InvalidProperties
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<string>>("invalidProperties");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set<ImmutableArray<string>?>(
                "invalidProperties",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    public ParseWebhookEventMetadata? Metadata
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ParseWebhookEventMetadata>("metadata");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("metadata", value);
        }
    }

    /// <summary>
    /// Presigned S3 URL for the input content uploaded to S3.
    /// </summary>
    public string? S3Url
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("s3URL");
        }
        init { this._rawData.Set("s3URL", value); }
    }

    /// <summary>
    /// Unique ID for each transformation output generated by bem following Segment's
    /// KSUID conventions.
    /// </summary>
    public string? TransformationID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("transformationID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("transformationID", value);
        }
    }

    /// <summary>
    /// Unique identifier of workflow that this event is associated with.
    /// </summary>
    public string? WorkflowID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("workflowID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowID", value);
        }
    }

    /// <summary>
    /// Name of workflow that this event is associated with.
    /// </summary>
    public string? WorkflowName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("workflowName");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowName", value);
        }
    }

    /// <summary>
    /// Version number of workflow that this event is associated with.
    /// </summary>
    public long? WorkflowVersionNum
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("workflowVersionNum");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowVersionNum", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.EventID;
        _ = this.FunctionID;
        _ = this.FunctionName;
        _ = this.ItemCount;
        _ = this.ItemOffset;
        _ = this.ReferenceID;
        _ = this.TransformedContent;
        _ = this.AvgConfidence;
        _ = this.CallID;
        this.CorrectedContent?.Validate();
        _ = this.CreatedAt;
        this.EventType?.Validate();
        _ = this.FieldBoundingBoxes;
        _ = this.FieldConfidences;
        _ = this.FunctionCallID;
        _ = this.FunctionCallTryNumber;
        _ = this.FunctionVersionNum;
        this.InboundEmail?.Validate();
        foreach (var item in this.Inputs ?? [])
        {
            item.Validate();
        }
        this.InputType?.Validate();
        _ = this.InvalidProperties;
        this.Metadata?.Validate();
        _ = this.S3Url;
        _ = this.TransformationID;
        _ = this.WorkflowID;
        _ = this.WorkflowName;
        _ = this.WorkflowVersionNum;
    }

    public ParseWebhookEvent() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ParseWebhookEvent(ParseWebhookEvent parseWebhookEvent)
        : base(parseWebhookEvent) { }
#pragma warning restore CS8618

    public ParseWebhookEvent(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ParseWebhookEvent(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ParseWebhookEventFromRaw.FromRawUnchecked"/>
    public static ParseWebhookEvent FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ParseWebhookEventFromRaw : IFromRawJson<ParseWebhookEvent>
{
    /// <inheritdoc/>
    public ParseWebhookEvent FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        ParseWebhookEvent.FromRawUnchecked(rawData);
}

/// <summary>
/// Corrected feedback provided for fine-tuning purposes.
/// </summary>
[JsonConverter(typeof(ParseWebhookEventCorrectedContentConverter))]
public record class ParseWebhookEventCorrectedContent : ModelBase
{
    public object? Value { get; } = null;

    JsonElement? _element = null;

    public JsonElement Json
    {
        get
        {
            return this._element ??= JsonSerializer.SerializeToElement(
                this.Value,
                ModelBase.SerializerOptions
            );
        }
    }

    public ParseWebhookEventCorrectedContent(
        ParseWebhookEventCorrectedContentOutput value,
        JsonElement? element = null
    )
    {
        this.Value = value;
        this._element = element;
    }

    public ParseWebhookEventCorrectedContent(
        IReadOnlyList<JsonElement> value,
        JsonElement? element = null
    )
    {
        this.Value = ImmutableArray.ToImmutableArray(value);
        this._element = element;
    }

    public ParseWebhookEventCorrectedContent(string value, JsonElement? element = null)
    {
        this.Value = value;
        this._element = element;
    }

    public ParseWebhookEventCorrectedContent(double value, JsonElement? element = null)
    {
        this.Value = value;
        this._element = element;
    }

    public ParseWebhookEventCorrectedContent(bool value, JsonElement? element = null)
    {
        this.Value = value;
        this._element = element;
    }

    public ParseWebhookEventCorrectedContent(JsonElement element)
    {
        this._element = element;
        this.Value = element;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="ParseWebhookEventCorrectedContentOutput"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickParseWebhookEventCorrectedContentOutput(out var value)) {
    ///     // `value` is of type `ParseWebhookEventCorrectedContentOutput`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickParseWebhookEventCorrectedContentOutput(
        [NotNullWhen(true)] out ParseWebhookEventCorrectedContentOutput? value
    )
    {
        value = this.Value as ParseWebhookEventCorrectedContentOutput;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="JsonElement"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickJsonElement(out var value)) {
    ///     // `value` is of type `JsonElement`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickJsonElement([NotNullWhen(true)] out JsonElement? value)
    {
        value = this.Value as JsonElement?;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="List{T}"/> where <c>T</c> is a <c>JsonElement</c>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickJsonElements(out var value)) {
    ///     // `value` is of type `IReadOnlyList&lt;JsonElement&gt;`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickJsonElements([NotNullWhen(true)] out IReadOnlyList<JsonElement>? value)
    {
        value = this.Value as IReadOnlyList<JsonElement>;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="string"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickString(out var value)) {
    ///     // `value` is of type `string`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickString([NotNullWhen(true)] out string? value)
    {
        value = this.Value as string;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="double"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickDouble(out var value)) {
    ///     // `value` is of type `double`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickDouble([NotNullWhen(true)] out double? value)
    {
        value = this.Value as double?;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="bool"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickBool(out var value)) {
    ///     // `value` is of type `bool`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickBool([NotNullWhen(true)] out bool? value)
    {
        value = this.Value as bool?;
        return value != null;
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Match"/>
    /// if you need your function parameters to return something.</para>
    ///
    /// <exception cref="BemInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// instance.Switch(
    ///     (ParseWebhookEventCorrectedContentOutput value) =&gt; {...},
    ///     (JsonElement value) =&gt; {...},
    ///     (IReadOnlyList&lt;JsonElement&gt; value) =&gt; {...},
    ///     (string value) =&gt; {...},
    ///     (double value) =&gt; {...},
    ///     (bool value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public void Switch(
        Action<ParseWebhookEventCorrectedContentOutput> parseWebhookEventCorrectedContentOutput,
        Action<JsonElement> jsonElement,
        Action<IReadOnlyList<JsonElement>> jsonElements,
        Action<string> @string,
        Action<double> @double,
        Action<bool> @bool
    )
    {
        switch (this.Value)
        {
            case ParseWebhookEventCorrectedContentOutput value:
                parseWebhookEventCorrectedContentOutput(value);
                break;
            case JsonElement value:
                jsonElement(value);
                break;
            case IReadOnlyList<JsonElement> value:
                jsonElements(value);
                break;
            case string value:
                @string(value);
                break;
            case double value:
                @double(value);
                break;
            case bool value:
                @bool(value);
                break;
            default:
                throw new BemInvalidDataException(
                    "Data did not match any variant of ParseWebhookEventCorrectedContent"
                );
        }
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with and
    /// returns its result.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Switch"/>
    /// if you don't need your function parameters to return a value.</para>
    ///
    /// <exception cref="BemInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// var result = instance.Match(
    ///     (ParseWebhookEventCorrectedContentOutput value) =&gt; {...},
    ///     (JsonElement value) =&gt; {...},
    ///     (IReadOnlyList&lt;JsonElement&gt; value) =&gt; {...},
    ///     (string value) =&gt; {...},
    ///     (double value) =&gt; {...},
    ///     (bool value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public T Match<T>(
        Func<ParseWebhookEventCorrectedContentOutput, T> parseWebhookEventCorrectedContentOutput,
        Func<JsonElement, T> jsonElement,
        Func<IReadOnlyList<JsonElement>, T> jsonElements,
        Func<string, T> @string,
        Func<double, T> @double,
        Func<bool, T> @bool
    )
    {
        return this.Value switch
        {
            ParseWebhookEventCorrectedContentOutput value =>
                parseWebhookEventCorrectedContentOutput(value),
            JsonElement value => jsonElement(value),
            IReadOnlyList<JsonElement> value => jsonElements(value),
            string value => @string(value),
            double value => @double(value),
            bool value => @bool(value),
            _ => throw new BemInvalidDataException(
                "Data did not match any variant of ParseWebhookEventCorrectedContent"
            ),
        };
    }

    public static implicit operator ParseWebhookEventCorrectedContent(
        ParseWebhookEventCorrectedContentOutput value
    ) => new(value);

    public static implicit operator ParseWebhookEventCorrectedContent(JsonElement value) =>
        new(value);

    public static implicit operator ParseWebhookEventCorrectedContent(List<JsonElement> value) =>
        new((IReadOnlyList<JsonElement>)value);

    public static implicit operator ParseWebhookEventCorrectedContent(string value) => new(value);

    public static implicit operator ParseWebhookEventCorrectedContent(double value) => new(value);

    public static implicit operator ParseWebhookEventCorrectedContent(bool value) => new(value);

    /// <summary>
    /// Validates that the instance was constructed with a known variant and that this variant is valid
    /// (based on its own <c>Validate</c> method).
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="BemInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public override void Validate()
    {
        if (this.Value == null)
        {
            throw new BemInvalidDataException(
                "Data did not match any variant of ParseWebhookEventCorrectedContent"
            );
        }
        this.Switch(
            (parseWebhookEventCorrectedContentOutput) =>
                parseWebhookEventCorrectedContentOutput.Validate(),
            (_) => { },
            (_) => { },
            (_) => { },
            (_) => { },
            (_) => { }
        );
    }

    public virtual bool Equals(ParseWebhookEventCorrectedContent? other) =>
        other != null
        && this.VariantIndex() == other.VariantIndex()
        && JsonElement.DeepEquals(this.Json, other.Json);

    public override int GetHashCode()
    {
        return 0;
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(this.Json),
            ModelBase.ToStringSerializerOptions
        );

    int VariantIndex()
    {
        return this.Value switch
        {
            ParseWebhookEventCorrectedContentOutput _ => 0,
            JsonElement _ => 1,
            IReadOnlyList<JsonElement> _ => 2,
            string _ => 3,
            double _ => 4,
            bool _ => 5,
            _ => -1,
        };
    }
}

sealed class ParseWebhookEventCorrectedContentConverter
    : JsonConverter<ParseWebhookEventCorrectedContent?>
{
    public override ParseWebhookEventCorrectedContent? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        var element = JsonSerializer.Deserialize<JsonElement>(ref reader, options);
        try
        {
            var deserialized = JsonSerializer.Deserialize<ParseWebhookEventCorrectedContentOutput>(
                element,
                options
            );
            if (deserialized != null)
            {
                deserialized.Validate();
                return new(deserialized, element);
            }
        }
        catch (Exception e) when (e is JsonException || e is BemInvalidDataException)
        {
            // ignore
        }

        try
        {
            var deserialized = JsonSerializer.Deserialize<List<JsonElement>>(element, options);
            if (deserialized != null)
            {
                return new(deserialized, element);
            }
        }
        catch (Exception e) when (e is JsonException || e is BemInvalidDataException)
        {
            // ignore
        }

        try
        {
            var deserialized = JsonSerializer.Deserialize<string>(element, options);
            if (deserialized != null)
            {
                return new(deserialized, element);
            }
        }
        catch (Exception e) when (e is JsonException || e is BemInvalidDataException)
        {
            // ignore
        }

        try
        {
            return new(JsonSerializer.Deserialize<double>(element, options), element);
        }
        catch (Exception e) when (e is JsonException || e is BemInvalidDataException)
        {
            // ignore
        }

        try
        {
            return new(JsonSerializer.Deserialize<bool>(element, options), element);
        }
        catch (Exception e) when (e is JsonException || e is BemInvalidDataException)
        {
            // ignore
        }

        try
        {
            return new(JsonSerializer.Deserialize<JsonElement>(element, options));
        }
        catch (Exception e) when (e is JsonException || e is BemInvalidDataException)
        {
            // ignore
        }

        return new(element);
    }

    public override void Write(
        Utf8JsonWriter writer,
        ParseWebhookEventCorrectedContent? value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value?.Json, options);
    }
}

[JsonConverter(
    typeof(JsonModelConverter<
        ParseWebhookEventCorrectedContentOutput,
        ParseWebhookEventCorrectedContentOutputFromRaw
    >)
)]
public sealed record class ParseWebhookEventCorrectedContentOutput : JsonModel
{
    public IReadOnlyList<AnyType?>? Output
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<AnyType?>>("output");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set<ImmutableArray<AnyType?>?>(
                "output",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        foreach (var item in this.Output ?? [])
        {
            item?.Validate();
        }
    }

    public ParseWebhookEventCorrectedContentOutput() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ParseWebhookEventCorrectedContentOutput(
        ParseWebhookEventCorrectedContentOutput parseWebhookEventCorrectedContentOutput
    )
        : base(parseWebhookEventCorrectedContentOutput) { }
#pragma warning restore CS8618

    public ParseWebhookEventCorrectedContentOutput(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ParseWebhookEventCorrectedContentOutput(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ParseWebhookEventCorrectedContentOutputFromRaw.FromRawUnchecked"/>
    public static ParseWebhookEventCorrectedContentOutput FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ParseWebhookEventCorrectedContentOutputFromRaw
    : IFromRawJson<ParseWebhookEventCorrectedContentOutput>
{
    /// <inheritdoc/>
    public ParseWebhookEventCorrectedContentOutput FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ParseWebhookEventCorrectedContentOutput.FromRawUnchecked(rawData);
}

[JsonConverter(typeof(ParseWebhookEventEventTypeConverter))]
public enum ParseWebhookEventEventType
{
    Parse,
}

sealed class ParseWebhookEventEventTypeConverter : JsonConverter<ParseWebhookEventEventType>
{
    public override ParseWebhookEventEventType Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "parse" => ParseWebhookEventEventType.Parse,
            _ => (ParseWebhookEventEventType)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        ParseWebhookEventEventType value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                ParseWebhookEventEventType.Parse => "parse",
                _ => throw new BemInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

[JsonConverter(typeof(JsonModelConverter<ParseWebhookEventInput, ParseWebhookEventInputFromRaw>))]
public sealed record class ParseWebhookEventInput : JsonModel
{
    public string? InputContent
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("inputContent");
        }
        init { this._rawData.Set("inputContent", value); }
    }

    public string? InputType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("inputType");
        }
        init { this._rawData.Set("inputType", value); }
    }

    public JsonElement? JsonInputContent
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<JsonElement>("jsonInputContent");
        }
        init { this._rawData.Set("jsonInputContent", value); }
    }

    public string? S3Url
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("s3URL");
        }
        init { this._rawData.Set("s3URL", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.InputContent;
        _ = this.InputType;
        _ = this.JsonInputContent;
        _ = this.S3Url;
    }

    public ParseWebhookEventInput() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ParseWebhookEventInput(ParseWebhookEventInput parseWebhookEventInput)
        : base(parseWebhookEventInput) { }
#pragma warning restore CS8618

    public ParseWebhookEventInput(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ParseWebhookEventInput(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ParseWebhookEventInputFromRaw.FromRawUnchecked"/>
    public static ParseWebhookEventInput FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ParseWebhookEventInputFromRaw : IFromRawJson<ParseWebhookEventInput>
{
    /// <inheritdoc/>
    public ParseWebhookEventInput FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ParseWebhookEventInput.FromRawUnchecked(rawData);
}

[JsonConverter(
    typeof(JsonModelConverter<ParseWebhookEventMetadata, ParseWebhookEventMetadataFromRaw>)
)]
public sealed record class ParseWebhookEventMetadata : JsonModel
{
    public double? DurationFunctionToEventSeconds
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>("durationFunctionToEventSeconds");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("durationFunctionToEventSeconds", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.DurationFunctionToEventSeconds;
    }

    public ParseWebhookEventMetadata() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public ParseWebhookEventMetadata(ParseWebhookEventMetadata parseWebhookEventMetadata)
        : base(parseWebhookEventMetadata) { }
#pragma warning restore CS8618

    public ParseWebhookEventMetadata(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    ParseWebhookEventMetadata(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ParseWebhookEventMetadataFromRaw.FromRawUnchecked"/>
    public static ParseWebhookEventMetadata FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ParseWebhookEventMetadataFromRaw : IFromRawJson<ParseWebhookEventMetadata>
{
    /// <inheritdoc/>
    public ParseWebhookEventMetadata FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => ParseWebhookEventMetadata.FromRawUnchecked(rawData);
}
