using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Bem.Core;
using Bem.Exceptions;
using Bem.Models.Errors;
using Bem.Models.Functions;

namespace Bem.Models.Webhooks;

[JsonConverter(typeof(JsonModelConverter<SendWebhookEvent, SendWebhookEventFromRaw>))]
public sealed record class SendWebhookEvent : JsonModel
{
    /// <summary>
    /// Outcome of a Send function's delivery attempt.
    /// </summary>
    public required ApiEnum<string, DeliveryStatus> DeliveryStatus
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ApiEnum<string, DeliveryStatus>>("deliveryStatus");
        }
        init { this._rawData.Set("deliveryStatus", value); }
    }

    /// <summary>
    /// Destination type for a Send function.
    /// </summary>
    public required ApiEnum<string, SendDestinationType> DestinationType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ApiEnum<string, SendDestinationType>>(
                "destinationType"
            );
        }
        init { this._rawData.Set("destinationType", value); }
    }

    /// <summary>
    /// Unique ID generated by bem to identify the event.
    /// </summary>
    public required string EventID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("eventID");
        }
        init { this._rawData.Set("eventID", value); }
    }

    /// <summary>
    /// Unique identifier of function that this event is associated with.
    /// </summary>
    public required string FunctionID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("functionID");
        }
        init { this._rawData.Set("functionID", value); }
    }

    /// <summary>
    /// Unique name of function that this event is associated with.
    /// </summary>
    public required string FunctionName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("functionName");
        }
        init { this._rawData.Set("functionName", value); }
    }

    /// <summary>
    /// The unique ID you use internally to refer to this data point, propagated from
    /// the original function input.
    /// </summary>
    public required string ReferenceID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("referenceID");
        }
        init { this._rawData.Set("referenceID", value); }
    }

    /// <summary>
    /// Unique identifier of workflow call that this event is associated with.
    /// </summary>
    public string? CallID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("callID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("callID", value);
        }
    }

    /// <summary>
    /// Timestamp indicating when the event was created.
    /// </summary>
    public DateTimeOffset? CreatedAt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<DateTimeOffset>("createdAt");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("createdAt", value);
        }
    }

    /// <summary>
    /// The full protocol event JSON that was delivered — identical to what subscription
    /// publish would deliver for the same event. For ad-hoc calls with a JSON file
    /// input, contains the raw input JSON. For ad-hoc calls with a binary file input,
    /// contains {"s3URL": "&lt;presigned-url&gt;"}.
    /// </summary>
    public JsonElement? DeliveredContent
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<JsonElement>("deliveredContent");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("deliveredContent", value);
        }
    }

    public ApiEnum<string, SendWebhookEventEventType>? EventType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, SendWebhookEventEventType>>(
                "eventType"
            );
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("eventType", value);
        }
    }

    /// <summary>
    /// Unique identifier of function call that this event is associated with.
    /// </summary>
    public string? FunctionCallID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("functionCallID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionCallID", value);
        }
    }

    /// <summary>
    /// The attempt number of the function call that created this event. 1 indexed.
    /// </summary>
    public long? FunctionCallTryNumber
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("functionCallTryNumber");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionCallTryNumber", value);
        }
    }

    /// <summary>
    /// Version number of function that this event is associated with.
    /// </summary>
    public long? FunctionVersionNum
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("functionVersionNum");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionVersionNum", value);
        }
    }

    /// <summary>
    /// Metadata returned when a Send function delivers to Google Drive.
    /// </summary>
    public GoogleDriveOutput? GoogleDriveOutput
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<GoogleDriveOutput>("googleDriveOutput");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("googleDriveOutput", value);
        }
    }

    /// <summary>
    /// The inbound email that triggered this event.
    /// </summary>
    public InboundEmailEvent? InboundEmail
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<InboundEmailEvent>("inboundEmail");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("inboundEmail", value);
        }
    }

    public SendWebhookEventMetadata? Metadata
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<SendWebhookEventMetadata>("metadata");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("metadata", value);
        }
    }

    /// <summary>
    /// Metadata returned when a Send function delivers to an S3 bucket.
    /// </summary>
    public S3Output? S3Output
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<S3Output>("s3Output");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("s3Output", value);
        }
    }

    /// <summary>
    /// Metadata returned when a Send function delivers to a webhook.
    /// </summary>
    public WebhookOutput? WebhookOutput
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<WebhookOutput>("webhookOutput");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("webhookOutput", value);
        }
    }

    /// <summary>
    /// Unique identifier of workflow that this event is associated with.
    /// </summary>
    public string? WorkflowID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("workflowID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowID", value);
        }
    }

    /// <summary>
    /// Name of workflow that this event is associated with.
    /// </summary>
    public string? WorkflowName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("workflowName");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowName", value);
        }
    }

    /// <summary>
    /// Version number of workflow that this event is associated with.
    /// </summary>
    public long? WorkflowVersionNum
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("workflowVersionNum");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowVersionNum", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        this.DeliveryStatus.Validate();
        this.DestinationType.Validate();
        _ = this.EventID;
        _ = this.FunctionID;
        _ = this.FunctionName;
        _ = this.ReferenceID;
        _ = this.CallID;
        _ = this.CreatedAt;
        _ = this.DeliveredContent;
        this.EventType?.Validate();
        _ = this.FunctionCallID;
        _ = this.FunctionCallTryNumber;
        _ = this.FunctionVersionNum;
        this.GoogleDriveOutput?.Validate();
        this.InboundEmail?.Validate();
        this.Metadata?.Validate();
        this.S3Output?.Validate();
        this.WebhookOutput?.Validate();
        _ = this.WorkflowID;
        _ = this.WorkflowName;
        _ = this.WorkflowVersionNum;
    }

    public SendWebhookEvent() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public SendWebhookEvent(SendWebhookEvent sendWebhookEvent)
        : base(sendWebhookEvent) { }
#pragma warning restore CS8618

    public SendWebhookEvent(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    SendWebhookEvent(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="SendWebhookEventFromRaw.FromRawUnchecked"/>
    public static SendWebhookEvent FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class SendWebhookEventFromRaw : IFromRawJson<SendWebhookEvent>
{
    /// <inheritdoc/>
    public SendWebhookEvent FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        SendWebhookEvent.FromRawUnchecked(rawData);
}

/// <summary>
/// Outcome of a Send function's delivery attempt.
/// </summary>
[JsonConverter(typeof(DeliveryStatusConverter))]
public enum DeliveryStatus
{
    Success,
    Skip,
}

sealed class DeliveryStatusConverter : JsonConverter<DeliveryStatus>
{
    public override DeliveryStatus Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "success" => DeliveryStatus.Success,
            "skip" => DeliveryStatus.Skip,
            _ => (DeliveryStatus)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        DeliveryStatus value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                DeliveryStatus.Success => "success",
                DeliveryStatus.Skip => "skip",
                _ => throw new BemInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

[JsonConverter(typeof(SendWebhookEventEventTypeConverter))]
public enum SendWebhookEventEventType
{
    Send,
}

sealed class SendWebhookEventEventTypeConverter : JsonConverter<SendWebhookEventEventType>
{
    public override SendWebhookEventEventType Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "send" => SendWebhookEventEventType.Send,
            _ => (SendWebhookEventEventType)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        SendWebhookEventEventType value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                SendWebhookEventEventType.Send => "send",
                _ => throw new BemInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// Metadata returned when a Send function delivers to Google Drive.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<GoogleDriveOutput, GoogleDriveOutputFromRaw>))]
public sealed record class GoogleDriveOutput : JsonModel
{
    /// <summary>
    /// Name of the file created in Google Drive.
    /// </summary>
    public required string FileName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("fileName");
        }
        init { this._rawData.Set("fileName", value); }
    }

    /// <summary>
    /// ID of the Google Drive folder the file was placed in.
    /// </summary>
    public required string FolderID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("folderID");
        }
        init { this._rawData.Set("folderID", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.FileName;
        _ = this.FolderID;
    }

    public GoogleDriveOutput() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public GoogleDriveOutput(GoogleDriveOutput googleDriveOutput)
        : base(googleDriveOutput) { }
#pragma warning restore CS8618

    public GoogleDriveOutput(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    GoogleDriveOutput(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="GoogleDriveOutputFromRaw.FromRawUnchecked"/>
    public static GoogleDriveOutput FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class GoogleDriveOutputFromRaw : IFromRawJson<GoogleDriveOutput>
{
    /// <inheritdoc/>
    public GoogleDriveOutput FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        GoogleDriveOutput.FromRawUnchecked(rawData);
}

[JsonConverter(
    typeof(JsonModelConverter<SendWebhookEventMetadata, SendWebhookEventMetadataFromRaw>)
)]
public sealed record class SendWebhookEventMetadata : JsonModel
{
    public double? DurationFunctionToEventSeconds
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>("durationFunctionToEventSeconds");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("durationFunctionToEventSeconds", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.DurationFunctionToEventSeconds;
    }

    public SendWebhookEventMetadata() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public SendWebhookEventMetadata(SendWebhookEventMetadata sendWebhookEventMetadata)
        : base(sendWebhookEventMetadata) { }
#pragma warning restore CS8618

    public SendWebhookEventMetadata(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    SendWebhookEventMetadata(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="SendWebhookEventMetadataFromRaw.FromRawUnchecked"/>
    public static SendWebhookEventMetadata FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class SendWebhookEventMetadataFromRaw : IFromRawJson<SendWebhookEventMetadata>
{
    /// <inheritdoc/>
    public SendWebhookEventMetadata FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => SendWebhookEventMetadata.FromRawUnchecked(rawData);
}

/// <summary>
/// Metadata returned when a Send function delivers to an S3 bucket.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<S3Output, S3OutputFromRaw>))]
public sealed record class S3Output : JsonModel
{
    /// <summary>
    /// Name of the S3 bucket the payload was written to.
    /// </summary>
    public required string BucketName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("bucketName");
        }
        init { this._rawData.Set("bucketName", value); }
    }

    /// <summary>
    /// Object key under which the payload was stored.
    /// </summary>
    public required string Key
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("key");
        }
        init { this._rawData.Set("key", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.BucketName;
        _ = this.Key;
    }

    public S3Output() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public S3Output(S3Output s3Output)
        : base(s3Output) { }
#pragma warning restore CS8618

    public S3Output(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    S3Output(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="S3OutputFromRaw.FromRawUnchecked"/>
    public static S3Output FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class S3OutputFromRaw : IFromRawJson<S3Output>
{
    /// <inheritdoc/>
    public S3Output FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        S3Output.FromRawUnchecked(rawData);
}

/// <summary>
/// Metadata returned when a Send function delivers to a webhook.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<WebhookOutput, WebhookOutputFromRaw>))]
public sealed record class WebhookOutput : JsonModel
{
    /// <summary>
    /// Raw HTTP response body returned by the webhook endpoint.
    /// </summary>
    public required string HttpResponseBody
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("httpResponseBody");
        }
        init { this._rawData.Set("httpResponseBody", value); }
    }

    /// <summary>
    /// HTTP status code returned by the webhook endpoint.
    /// </summary>
    public required long HttpStatusCode
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("httpStatusCode");
        }
        init { this._rawData.Set("httpStatusCode", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.HttpResponseBody;
        _ = this.HttpStatusCode;
    }

    public WebhookOutput() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public WebhookOutput(WebhookOutput webhookOutput)
        : base(webhookOutput) { }
#pragma warning restore CS8618

    public WebhookOutput(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    WebhookOutput(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="WebhookOutputFromRaw.FromRawUnchecked"/>
    public static WebhookOutput FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class WebhookOutputFromRaw : IFromRawJson<WebhookOutput>
{
    /// <inheritdoc/>
    public WebhookOutput FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        WebhookOutput.FromRawUnchecked(rawData);
}
