using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Bem.Core;
using Bem.Exceptions;
using Bem.Models.Errors;

namespace Bem.Models.Webhooks;

[JsonConverter(typeof(JsonModelConverter<SplitItemWebhookEvent, SplitItemWebhookEventFromRaw>))]
public sealed record class SplitItemWebhookEvent : JsonModel
{
    /// <summary>
    /// Unique ID generated by bem to identify the event.
    /// </summary>
    public required string EventID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("eventID");
        }
        init { this._rawData.Set("eventID", value); }
    }

    /// <summary>
    /// Unique identifier of function that this event is associated with.
    /// </summary>
    public required string FunctionID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("functionID");
        }
        init { this._rawData.Set("functionID", value); }
    }

    /// <summary>
    /// Unique name of function that this event is associated with.
    /// </summary>
    public required string FunctionName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("functionName");
        }
        init { this._rawData.Set("functionName", value); }
    }

    public required ApiEnum<string, SplitItemWebhookEventOutputType> OutputType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ApiEnum<string, SplitItemWebhookEventOutputType>>(
                "outputType"
            );
        }
        init { this._rawData.Set("outputType", value); }
    }

    /// <summary>
    /// The unique ID you use internally to refer to this data point, propagated from
    /// the original function input.
    /// </summary>
    public required string ReferenceID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("referenceID");
        }
        init { this._rawData.Set("referenceID", value); }
    }

    /// <summary>
    /// Unique identifier of workflow call that this event is associated with.
    /// </summary>
    public string? CallID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("callID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("callID", value);
        }
    }

    /// <summary>
    /// Timestamp indicating when the event was created.
    /// </summary>
    public DateTimeOffset? CreatedAt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<DateTimeOffset>("createdAt");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("createdAt", value);
        }
    }

    public ApiEnum<string, SplitItemWebhookEventEventType>? EventType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, SplitItemWebhookEventEventType>>(
                "eventType"
            );
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("eventType", value);
        }
    }

    /// <summary>
    /// Unique identifier of function call that this event is associated with.
    /// </summary>
    public string? FunctionCallID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("functionCallID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionCallID", value);
        }
    }

    /// <summary>
    /// The attempt number of the function call that created this event. 1 indexed.
    /// </summary>
    public long? FunctionCallTryNumber
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("functionCallTryNumber");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionCallTryNumber", value);
        }
    }

    /// <summary>
    /// Version number of function that this event is associated with.
    /// </summary>
    public long? FunctionVersionNum
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("functionVersionNum");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionVersionNum", value);
        }
    }

    /// <summary>
    /// The inbound email that triggered this event.
    /// </summary>
    public InboundEmailEvent? InboundEmail
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<InboundEmailEvent>("inboundEmail");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("inboundEmail", value);
        }
    }

    public SplitItemWebhookEventMetadata? Metadata
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<SplitItemWebhookEventMetadata>("metadata");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("metadata", value);
        }
    }

    public SplitItemWebhookEventPrintPageOutput? PrintPageOutput
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<SplitItemWebhookEventPrintPageOutput>(
                "printPageOutput"
            );
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("printPageOutput", value);
        }
    }

    public SplitItemWebhookEventSemanticPageOutput? SemanticPageOutput
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<SplitItemWebhookEventSemanticPageOutput>(
                "semanticPageOutput"
            );
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("semanticPageOutput", value);
        }
    }

    /// <summary>
    /// Unique identifier of workflow that this event is associated with.
    /// </summary>
    public string? WorkflowID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("workflowID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowID", value);
        }
    }

    /// <summary>
    /// Name of workflow that this event is associated with.
    /// </summary>
    public string? WorkflowName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("workflowName");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowName", value);
        }
    }

    /// <summary>
    /// Version number of workflow that this event is associated with.
    /// </summary>
    public long? WorkflowVersionNum
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("workflowVersionNum");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowVersionNum", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.EventID;
        _ = this.FunctionID;
        _ = this.FunctionName;
        this.OutputType.Validate();
        _ = this.ReferenceID;
        _ = this.CallID;
        _ = this.CreatedAt;
        this.EventType?.Validate();
        _ = this.FunctionCallID;
        _ = this.FunctionCallTryNumber;
        _ = this.FunctionVersionNum;
        this.InboundEmail?.Validate();
        this.Metadata?.Validate();
        this.PrintPageOutput?.Validate();
        this.SemanticPageOutput?.Validate();
        _ = this.WorkflowID;
        _ = this.WorkflowName;
        _ = this.WorkflowVersionNum;
    }

    public SplitItemWebhookEvent() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public SplitItemWebhookEvent(SplitItemWebhookEvent splitItemWebhookEvent)
        : base(splitItemWebhookEvent) { }
#pragma warning restore CS8618

    public SplitItemWebhookEvent(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    SplitItemWebhookEvent(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="SplitItemWebhookEventFromRaw.FromRawUnchecked"/>
    public static SplitItemWebhookEvent FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class SplitItemWebhookEventFromRaw : IFromRawJson<SplitItemWebhookEvent>
{
    /// <inheritdoc/>
    public SplitItemWebhookEvent FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => SplitItemWebhookEvent.FromRawUnchecked(rawData);
}

[JsonConverter(typeof(SplitItemWebhookEventOutputTypeConverter))]
public enum SplitItemWebhookEventOutputType
{
    PrintPage,
    SemanticPage,
}

sealed class SplitItemWebhookEventOutputTypeConverter
    : JsonConverter<SplitItemWebhookEventOutputType>
{
    public override SplitItemWebhookEventOutputType Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "print_page" => SplitItemWebhookEventOutputType.PrintPage,
            "semantic_page" => SplitItemWebhookEventOutputType.SemanticPage,
            _ => (SplitItemWebhookEventOutputType)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        SplitItemWebhookEventOutputType value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                SplitItemWebhookEventOutputType.PrintPage => "print_page",
                SplitItemWebhookEventOutputType.SemanticPage => "semantic_page",
                _ => throw new BemInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

[JsonConverter(typeof(SplitItemWebhookEventEventTypeConverter))]
public enum SplitItemWebhookEventEventType
{
    SplitItem,
}

sealed class SplitItemWebhookEventEventTypeConverter : JsonConverter<SplitItemWebhookEventEventType>
{
    public override SplitItemWebhookEventEventType Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "split_item" => SplitItemWebhookEventEventType.SplitItem,
            _ => (SplitItemWebhookEventEventType)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        SplitItemWebhookEventEventType value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                SplitItemWebhookEventEventType.SplitItem => "split_item",
                _ => throw new BemInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

[JsonConverter(
    typeof(JsonModelConverter<SplitItemWebhookEventMetadata, SplitItemWebhookEventMetadataFromRaw>)
)]
public sealed record class SplitItemWebhookEventMetadata : JsonModel
{
    public double? DurationFunctionToEventSeconds
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>("durationFunctionToEventSeconds");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("durationFunctionToEventSeconds", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.DurationFunctionToEventSeconds;
    }

    public SplitItemWebhookEventMetadata() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public SplitItemWebhookEventMetadata(
        SplitItemWebhookEventMetadata splitItemWebhookEventMetadata
    )
        : base(splitItemWebhookEventMetadata) { }
#pragma warning restore CS8618

    public SplitItemWebhookEventMetadata(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    SplitItemWebhookEventMetadata(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="SplitItemWebhookEventMetadataFromRaw.FromRawUnchecked"/>
    public static SplitItemWebhookEventMetadata FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class SplitItemWebhookEventMetadataFromRaw : IFromRawJson<SplitItemWebhookEventMetadata>
{
    /// <inheritdoc/>
    public SplitItemWebhookEventMetadata FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => SplitItemWebhookEventMetadata.FromRawUnchecked(rawData);
}

[JsonConverter(
    typeof(JsonModelConverter<
        SplitItemWebhookEventPrintPageOutput,
        SplitItemWebhookEventPrintPageOutputFromRaw
    >)
)]
public sealed record class SplitItemWebhookEventPrintPageOutput : JsonModel
{
    public string? CollectionReferenceID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("collectionReferenceID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("collectionReferenceID", value);
        }
    }

    public long? ItemCount
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemCount");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemCount", value);
        }
    }

    public long? ItemOffset
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemOffset");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemOffset", value);
        }
    }

    public string? S3Url
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("s3URL");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("s3URL", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.CollectionReferenceID;
        _ = this.ItemCount;
        _ = this.ItemOffset;
        _ = this.S3Url;
    }

    public SplitItemWebhookEventPrintPageOutput() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public SplitItemWebhookEventPrintPageOutput(
        SplitItemWebhookEventPrintPageOutput splitItemWebhookEventPrintPageOutput
    )
        : base(splitItemWebhookEventPrintPageOutput) { }
#pragma warning restore CS8618

    public SplitItemWebhookEventPrintPageOutput(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    SplitItemWebhookEventPrintPageOutput(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="SplitItemWebhookEventPrintPageOutputFromRaw.FromRawUnchecked"/>
    public static SplitItemWebhookEventPrintPageOutput FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class SplitItemWebhookEventPrintPageOutputFromRaw
    : IFromRawJson<SplitItemWebhookEventPrintPageOutput>
{
    /// <inheritdoc/>
    public SplitItemWebhookEventPrintPageOutput FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => SplitItemWebhookEventPrintPageOutput.FromRawUnchecked(rawData);
}

[JsonConverter(
    typeof(JsonModelConverter<
        SplitItemWebhookEventSemanticPageOutput,
        SplitItemWebhookEventSemanticPageOutputFromRaw
    >)
)]
public sealed record class SplitItemWebhookEventSemanticPageOutput : JsonModel
{
    public string? CollectionReferenceID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("collectionReferenceID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("collectionReferenceID", value);
        }
    }

    public string? ItemClass
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("itemClass");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemClass", value);
        }
    }

    public long? ItemClassCount
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemClassCount");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemClassCount", value);
        }
    }

    public long? ItemClassOffset
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemClassOffset");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemClassOffset", value);
        }
    }

    public long? ItemCount
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemCount");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemCount", value);
        }
    }

    public long? ItemOffset
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemOffset");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemOffset", value);
        }
    }

    public long? PageCount
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("pageCount");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("pageCount", value);
        }
    }

    public long? PageEnd
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("pageEnd");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("pageEnd", value);
        }
    }

    public long? PageStart
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("pageStart");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("pageStart", value);
        }
    }

    public string? S3Url
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("s3URL");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("s3URL", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.CollectionReferenceID;
        _ = this.ItemClass;
        _ = this.ItemClassCount;
        _ = this.ItemClassOffset;
        _ = this.ItemCount;
        _ = this.ItemOffset;
        _ = this.PageCount;
        _ = this.PageEnd;
        _ = this.PageStart;
        _ = this.S3Url;
    }

    public SplitItemWebhookEventSemanticPageOutput() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public SplitItemWebhookEventSemanticPageOutput(
        SplitItemWebhookEventSemanticPageOutput splitItemWebhookEventSemanticPageOutput
    )
        : base(splitItemWebhookEventSemanticPageOutput) { }
#pragma warning restore CS8618

    public SplitItemWebhookEventSemanticPageOutput(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    SplitItemWebhookEventSemanticPageOutput(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="SplitItemWebhookEventSemanticPageOutputFromRaw.FromRawUnchecked"/>
    public static SplitItemWebhookEventSemanticPageOutput FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class SplitItemWebhookEventSemanticPageOutputFromRaw
    : IFromRawJson<SplitItemWebhookEventSemanticPageOutput>
{
    /// <inheritdoc/>
    public SplitItemWebhookEventSemanticPageOutput FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => SplitItemWebhookEventSemanticPageOutput.FromRawUnchecked(rawData);
}
