using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Bem.Core;
using Bem.Exceptions;
using Bem.Models.Errors;

namespace Bem.Models.Webhooks;

[JsonConverter(
    typeof(JsonModelConverter<SplitCollectionWebhookEvent, SplitCollectionWebhookEventFromRaw>)
)]
public sealed record class SplitCollectionWebhookEvent : JsonModel
{
    /// <summary>
    /// Unique ID generated by bem to identify the event.
    /// </summary>
    public required string EventID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("eventID");
        }
        init { this._rawData.Set("eventID", value); }
    }

    /// <summary>
    /// Unique identifier of function that this event is associated with.
    /// </summary>
    public required string FunctionID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("functionID");
        }
        init { this._rawData.Set("functionID", value); }
    }

    /// <summary>
    /// Unique name of function that this event is associated with.
    /// </summary>
    public required string FunctionName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("functionName");
        }
        init { this._rawData.Set("functionName", value); }
    }

    public required ApiEnum<string, OutputType> OutputType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ApiEnum<string, OutputType>>("outputType");
        }
        init { this._rawData.Set("outputType", value); }
    }

    public required PrintPageOutput PrintPageOutput
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<PrintPageOutput>("printPageOutput");
        }
        init { this._rawData.Set("printPageOutput", value); }
    }

    /// <summary>
    /// The unique ID you use internally to refer to this data point, propagated from
    /// the original function input.
    /// </summary>
    public required string ReferenceID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("referenceID");
        }
        init { this._rawData.Set("referenceID", value); }
    }

    public required SemanticPageOutput SemanticPageOutput
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<SemanticPageOutput>("semanticPageOutput");
        }
        init { this._rawData.Set("semanticPageOutput", value); }
    }

    /// <summary>
    /// Unique identifier of workflow call that this event is associated with.
    /// </summary>
    public string? CallID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("callID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("callID", value);
        }
    }

    /// <summary>
    /// Timestamp indicating when the event was created.
    /// </summary>
    public DateTimeOffset? CreatedAt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<DateTimeOffset>("createdAt");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("createdAt", value);
        }
    }

    public ApiEnum<string, SplitCollectionWebhookEventEventType>? EventType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<
                ApiEnum<string, SplitCollectionWebhookEventEventType>
            >("eventType");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("eventType", value);
        }
    }

    /// <summary>
    /// Unique identifier of function call that this event is associated with.
    /// </summary>
    public string? FunctionCallID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("functionCallID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionCallID", value);
        }
    }

    /// <summary>
    /// The attempt number of the function call that created this event. 1 indexed.
    /// </summary>
    public long? FunctionCallTryNumber
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("functionCallTryNumber");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionCallTryNumber", value);
        }
    }

    /// <summary>
    /// Version number of function that this event is associated with.
    /// </summary>
    public long? FunctionVersionNum
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("functionVersionNum");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("functionVersionNum", value);
        }
    }

    /// <summary>
    /// The inbound email that triggered this event.
    /// </summary>
    public InboundEmailEvent? InboundEmail
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<InboundEmailEvent>("inboundEmail");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("inboundEmail", value);
        }
    }

    public SplitCollectionWebhookEventMetadata? Metadata
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<SplitCollectionWebhookEventMetadata>("metadata");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("metadata", value);
        }
    }

    /// <summary>
    /// Unique identifier of workflow that this event is associated with.
    /// </summary>
    public string? WorkflowID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("workflowID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowID", value);
        }
    }

    /// <summary>
    /// Name of workflow that this event is associated with.
    /// </summary>
    public string? WorkflowName
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("workflowName");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowName", value);
        }
    }

    /// <summary>
    /// Version number of workflow that this event is associated with.
    /// </summary>
    public long? WorkflowVersionNum
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("workflowVersionNum");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("workflowVersionNum", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.EventID;
        _ = this.FunctionID;
        _ = this.FunctionName;
        this.OutputType.Validate();
        this.PrintPageOutput.Validate();
        _ = this.ReferenceID;
        this.SemanticPageOutput.Validate();
        _ = this.CallID;
        _ = this.CreatedAt;
        this.EventType?.Validate();
        _ = this.FunctionCallID;
        _ = this.FunctionCallTryNumber;
        _ = this.FunctionVersionNum;
        this.InboundEmail?.Validate();
        this.Metadata?.Validate();
        _ = this.WorkflowID;
        _ = this.WorkflowName;
        _ = this.WorkflowVersionNum;
    }

    public SplitCollectionWebhookEvent() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public SplitCollectionWebhookEvent(SplitCollectionWebhookEvent splitCollectionWebhookEvent)
        : base(splitCollectionWebhookEvent) { }
#pragma warning restore CS8618

    public SplitCollectionWebhookEvent(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    SplitCollectionWebhookEvent(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="SplitCollectionWebhookEventFromRaw.FromRawUnchecked"/>
    public static SplitCollectionWebhookEvent FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class SplitCollectionWebhookEventFromRaw : IFromRawJson<SplitCollectionWebhookEvent>
{
    /// <inheritdoc/>
    public SplitCollectionWebhookEvent FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => SplitCollectionWebhookEvent.FromRawUnchecked(rawData);
}

[JsonConverter(typeof(OutputTypeConverter))]
public enum OutputType
{
    PrintPage,
    SemanticPage,
}

sealed class OutputTypeConverter : JsonConverter<OutputType>
{
    public override OutputType Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "print_page" => OutputType.PrintPage,
            "semantic_page" => OutputType.SemanticPage,
            _ => (OutputType)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        OutputType value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                OutputType.PrintPage => "print_page",
                OutputType.SemanticPage => "semantic_page",
                _ => throw new BemInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

[JsonConverter(typeof(JsonModelConverter<PrintPageOutput, PrintPageOutputFromRaw>))]
public sealed record class PrintPageOutput : JsonModel
{
    public long? ItemCount
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemCount");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemCount", value);
        }
    }

    public IReadOnlyList<Item>? Items
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<Item>>("items");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set<ImmutableArray<Item>?>(
                "items",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ItemCount;
        foreach (var item in this.Items ?? [])
        {
            item.Validate();
        }
    }

    public PrintPageOutput() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public PrintPageOutput(PrintPageOutput printPageOutput)
        : base(printPageOutput) { }
#pragma warning restore CS8618

    public PrintPageOutput(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    PrintPageOutput(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="PrintPageOutputFromRaw.FromRawUnchecked"/>
    public static PrintPageOutput FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class PrintPageOutputFromRaw : IFromRawJson<PrintPageOutput>
{
    /// <inheritdoc/>
    public PrintPageOutput FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        PrintPageOutput.FromRawUnchecked(rawData);
}

[JsonConverter(typeof(JsonModelConverter<Item, ItemFromRaw>))]
public sealed record class Item : JsonModel
{
    public long? ItemOffset
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemOffset");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemOffset", value);
        }
    }

    public string? ItemReferenceID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("itemReferenceID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemReferenceID", value);
        }
    }

    public string? S3Url
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("s3URL");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("s3URL", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ItemOffset;
        _ = this.ItemReferenceID;
        _ = this.S3Url;
    }

    public Item() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public Item(Item item)
        : base(item) { }
#pragma warning restore CS8618

    public Item(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Item(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="ItemFromRaw.FromRawUnchecked"/>
    public static Item FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class ItemFromRaw : IFromRawJson<Item>
{
    /// <inheritdoc/>
    public Item FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        Item.FromRawUnchecked(rawData);
}

[JsonConverter(typeof(JsonModelConverter<SemanticPageOutput, SemanticPageOutputFromRaw>))]
public sealed record class SemanticPageOutput : JsonModel
{
    public long? ItemCount
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemCount");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemCount", value);
        }
    }

    public IReadOnlyList<SemanticPageOutputItem>? Items
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<SemanticPageOutputItem>>("items");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set<ImmutableArray<SemanticPageOutputItem>?>(
                "items",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    public long? PageCount
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("pageCount");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("pageCount", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ItemCount;
        foreach (var item in this.Items ?? [])
        {
            item.Validate();
        }
        _ = this.PageCount;
    }

    public SemanticPageOutput() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public SemanticPageOutput(SemanticPageOutput semanticPageOutput)
        : base(semanticPageOutput) { }
#pragma warning restore CS8618

    public SemanticPageOutput(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    SemanticPageOutput(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="SemanticPageOutputFromRaw.FromRawUnchecked"/>
    public static SemanticPageOutput FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class SemanticPageOutputFromRaw : IFromRawJson<SemanticPageOutput>
{
    /// <inheritdoc/>
    public SemanticPageOutput FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        SemanticPageOutput.FromRawUnchecked(rawData);
}

[JsonConverter(typeof(JsonModelConverter<SemanticPageOutputItem, SemanticPageOutputItemFromRaw>))]
public sealed record class SemanticPageOutputItem : JsonModel
{
    public string? ItemClass
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("itemClass");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemClass", value);
        }
    }

    public long? ItemClassCount
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemClassCount");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemClassCount", value);
        }
    }

    public long? ItemClassOffset
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemClassOffset");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemClassOffset", value);
        }
    }

    public long? ItemOffset
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("itemOffset");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemOffset", value);
        }
    }

    public string? ItemReferenceID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("itemReferenceID");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("itemReferenceID", value);
        }
    }

    public long? PageEnd
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("pageEnd");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("pageEnd", value);
        }
    }

    public long? PageStart
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>("pageStart");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("pageStart", value);
        }
    }

    public string? S3Url
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("s3URL");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("s3URL", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ItemClass;
        _ = this.ItemClassCount;
        _ = this.ItemClassOffset;
        _ = this.ItemOffset;
        _ = this.ItemReferenceID;
        _ = this.PageEnd;
        _ = this.PageStart;
        _ = this.S3Url;
    }

    public SemanticPageOutputItem() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public SemanticPageOutputItem(SemanticPageOutputItem semanticPageOutputItem)
        : base(semanticPageOutputItem) { }
#pragma warning restore CS8618

    public SemanticPageOutputItem(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    SemanticPageOutputItem(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="SemanticPageOutputItemFromRaw.FromRawUnchecked"/>
    public static SemanticPageOutputItem FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class SemanticPageOutputItemFromRaw : IFromRawJson<SemanticPageOutputItem>
{
    /// <inheritdoc/>
    public SemanticPageOutputItem FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => SemanticPageOutputItem.FromRawUnchecked(rawData);
}

[JsonConverter(typeof(SplitCollectionWebhookEventEventTypeConverter))]
public enum SplitCollectionWebhookEventEventType
{
    SplitCollection,
}

sealed class SplitCollectionWebhookEventEventTypeConverter
    : JsonConverter<SplitCollectionWebhookEventEventType>
{
    public override SplitCollectionWebhookEventEventType Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "split_collection" => SplitCollectionWebhookEventEventType.SplitCollection,
            _ => (SplitCollectionWebhookEventEventType)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        SplitCollectionWebhookEventEventType value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                SplitCollectionWebhookEventEventType.SplitCollection => "split_collection",
                _ => throw new BemInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

[JsonConverter(
    typeof(JsonModelConverter<
        SplitCollectionWebhookEventMetadata,
        SplitCollectionWebhookEventMetadataFromRaw
    >)
)]
public sealed record class SplitCollectionWebhookEventMetadata : JsonModel
{
    public double? DurationFunctionToEventSeconds
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>("durationFunctionToEventSeconds");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("durationFunctionToEventSeconds", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.DurationFunctionToEventSeconds;
    }

    public SplitCollectionWebhookEventMetadata() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public SplitCollectionWebhookEventMetadata(
        SplitCollectionWebhookEventMetadata splitCollectionWebhookEventMetadata
    )
        : base(splitCollectionWebhookEventMetadata) { }
#pragma warning restore CS8618

    public SplitCollectionWebhookEventMetadata(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    SplitCollectionWebhookEventMetadata(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="SplitCollectionWebhookEventMetadataFromRaw.FromRawUnchecked"/>
    public static SplitCollectionWebhookEventMetadata FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class SplitCollectionWebhookEventMetadataFromRaw : IFromRawJson<SplitCollectionWebhookEventMetadata>
{
    /// <inheritdoc/>
    public SplitCollectionWebhookEventMetadata FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => SplitCollectionWebhookEventMetadata.FromRawUnchecked(rawData);
}
